#Handle missing value

In [22]:
 #ENCODING
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
data ={"colors": ['red', 'green', 'yellow', 'green','red',np.nan]}
df=pd.DataFrame(data)
df
#handle null values
df=df.dropna()
print(df)




   colors
0     red
1   green
2  yellow
3   green
4     red


In [36]:

#label Encoding
from sklearn.preprocessing import LabelEncoder
print(df)
le=LabelEncoder()
df["colors_encoder"]=le.fit_transform(df["colors"])
df["colors_encoder1"]=le.fit_transform(df["colors"])
df.drop(["colors_encoder","colors_encoder1"],axis=1,inplace=True)
df

   colors
0     red
1   green
2  yellow
3   green
4     red


,colors
0,red
1,green
2,yellow
3,green
4,red


**#one Hot Encoder**

In [49]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import OneHotEncoder
import pandas as pd
print(df)
#one hot Encoding
# Create one-hot encoded columns(by the help of sklearn)
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[["colors"]])
print(encoded.toarray())
# Create one-hot encoded columns(by the help of pandas)
encoded_df = pd.get_dummies(df, columns=['colors'])
print(encoded_df)

   colors
0     red
1   green
2  yellow
3   green
4     red
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
   colors_green  colors_red  colors_yellow
0         False        True          False
1          True       False          False
2         False       False           True
3          True       False          False
4         False        True          False


In [55]:
#combination of handling missing values | label encoding |onehot encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import label_binarize,OneHotEncoder
data={
    "age":[12,34,np.nan,56,67],
    "name":["dheeraj","kunal","yash","anushka","nikita"],
    "gender":["male","male","male","femle",np.nan]
}
df=pd.DataFrame(data)
print("-------------handling missing values---------")
df["age"]=df["age"].fillna(df["age"].mean())
print(df)
df.dropna(subset=["gender"],inplace=True)
print(df)
print("-----------------label encoding-------------")
lb=LabelEncoder()
df["gender1"]=lb.fit_transform(df["gender"])
print(df)

print("----------------one hot encoding--------------")
on=OneHotEncoder()
on_e=on.fit_transform(df[["gender"]]).toarray()
print(on_e)

-------------handling missing values---------
     age     name gender
0  12.00  dheeraj   male
1  34.00    kunal   male
2  42.25     yash   male
3  56.00  anushka  femle
4  67.00   nikita    NaN
     age     name gender
0  12.00  dheeraj   male
1  34.00    kunal   male
2  42.25     yash   male
3  56.00  anushka  femle
-----------------label encoding-------------
     age     name gender  gender1
0  12.00  dheeraj   male        1
1  34.00    kunal   male        1
2  42.25     yash   male        1
3  56.00  anushka  femle        0
----------------one hot encoding--------------
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]
