**numPy**

In [ ]:
#numPy
import numpy

**numPy run in vscode**

1.python -v

2.python -m venv folderName

3. ./venv/scripts/activate.bat

4. pip install numpy

5.pythan filename.py

6.deactivate


In [27]:
import numpy
print("<----------modules written method--------->")
# #import numpy as np
# #from numpy import arange
# from numpy import *


# print("<-----------Example1--------->")
# n=numpy.arange(11)
# print(type(n))
# print(n)
# print(n[0])



# print("<--------------example 2--------------->")
# n=numpy.arange(12)
# d=n.reshape(3,4)  #reshap(row,column)//2D array
# print(type(d))
# print(d)






# example3
# print("<------------Exapmle3------------->")
# n=numpy.arange(24).reshape(1,6,4)#3d Array
# print(type(n))
# print(n)

#example 4.
# print("<------------Exapmle 4------------->")
# n=numpy.arange(12).reshape(4,3)#3d Array
# print(type(n))
# # print(n[:,-1])
# print(n[0:4,2:])


#Example 5.
# print("<------------Exapmle 5------------->")
# n=numpy.arange(12).reshape(4,3)#3d Array
# # print(type(n))
# print(n)
# print(n[1:3,1])
# print(n[1:3,1:2])



<------------Exapmle 5------------->
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[4 7]
[[4]
 [7]]
