**Reshap in numpy**

In [ ]:
#reshape
import numpy as np
# arr=np.arange(12)
# up_arr=np.reshape(arr,(3,4))# 3->row, 4->column
# print(up_arr)


#Example 2
# arr=np.arange(10)
# n=np.reshape(arr,(2,1,5))
# print(n)


#example 3
arr=np.arange(10)
n=np.reshape(arr,(2,1,5))
# print(n)
print(n[:1,:,2:3])



[[[2]]]


**Flatten**

#Flatten(convert nd array -> 1d array)(make a copy of array and make change in array not affect the original array )
# it create a copy of array
import numpy as np
# arr=np.arange(12).reshape(3,4)
# print(arr)
# print("----------")
# up_arr=arr.flatten()
# print(up_arr)
# print(arr)




#example 2. (for 3d Array)
arr=np.arange(48).reshape(3,4,4)
print(arr)
print("----------")
up_arr=arr.flatten()
print(up_arr)
print(arr)




**Ravel**

In [ ]:
#ravel(change in element of array mae effect the oniginal array)
import numpy as np
# arr=np.arange(14).reshape(7,2)
# up_arr=arr.ravel()
# print(up_arr)



#example 2.(3D)
arr=np.arange(6).reshape(3,2)
up_arr=arr.ravel()
print(up_arr)
print(arr.ravel())
up_arr[0]=12 #(change in original array)
print(arr)



**transpose**

In [24]:
#Transpose of Matrix

import numpy as np
# arr=np.arange(12).reshape(3,4)
# print(arr)
# up_arr=arr.T
# print(up_arr)


# exapmle 2.
arr=np.arange(12).reshape(3,2,2)
print(arr)
print("-------")
up_arr=arr.T
print(up_arr)



[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
-------
[[[ 0  4  8]
  [ 2  6 10]]

 [[ 1  5  9]
  [ 3  7 11]]]


**Slicing**

In [44]:
#slicing for 1D

import numpy as np
# arr=np.arange(11)
# print(arr)

# up_arr=arr[:3]
# print(up_arr)

#slicing for 2D
# arr=np.arange(12).reshape(3,4)
# print(arr)

# up_arr=arr[:2,:1]
# print(up_arr)
# slicing for 3D
arr=np.arange(24).reshape(3,4,2)
print(arr)
# up_arr1=arr[0:1,0:1,0:1]
# up_arr2=arr[2:,3:,1:]
print(arr[::2,::3,1])
# print(up_arr1)
# print(up_arr2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[ 1  7]
 [17 23]]


**Looping in numpy**

1.   While
2.   for loop



In [69]:
#While for 1D
import numpy as np
# arr=np.arange(12)
# i=0
# while i<len(arr):
#   print(arr[i]," ",end="")
#   i+=1


#While for 2D
arr=np.arange(12).reshape(3,4)
i=0
print(len(arr))
while i<len(arr):
  j=0
  while j < len(arr[i]):
    print(arr[i][j]," ",end="")
    j+=1
  i+=1
#While for 3D
# arr=np.arange(12).reshape(3,4)
# print(arr)
# i,j,k=0,0,0
# while i<len(arr):
#   while j<i:
#     while k<j:
#       print(arr[k]," ",end="")
#       k+=1
#     j+=1
#   i+=1

3
0  1  2  3  4  5  6  7  8  9  10  11  

**for Loop**

In [94]:
#Example 1.
import numpy as np

arr=np.arange(16).reshape(4,4)
print(arr)
i=0
while i<len(arr):
  j=0
  while j< len(arr[i]):
    if(i==j):
      arr[i][j] = 1
    else:
      arr[i][j]=0
    # print(arr[i][j])
    j+=1
  i += 1
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
